sudo: required
services:
  - docker

before_install:
  - docker build -t josel82/docker-react-app -f Dockerfile.dev .

script:
  - docker run josel82/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-127978173339"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"